### ISSUE TITLE
black screen after installing chill

### ISSUE THREAD

**Issue by alekksander** [MarianArlt/kde-plasma-chili#12]
as title says — i can see only cursor on black screen after installing and applying Your theme. editing etc/sddm.conf and removing chill is a necessity to have desktop back. 

16.04/5.13.3

**Comment by MarianArlt** [comment]
Assuming from your comment 

> [...] removing chill [...]

 It seems you accidentally installed [Chili for stand-alone SDDM](https://github.com/MarianArlt/sddm-chili). For some reason people have had issues running that version on systems with Plasma as their desktop environment, that's why I **discourage** and from installing it on such systems in the [README](https://github.com/MarianArlt/kde-plasma-chili/blob/master/README.md). Please review your Chili version!
