### ISSUE TITLE
Allow choosing the font

### ISSUE THREAD

**Issue by flipwise** [MarianArlt/kde-plasma-chili#15]
Hi there,

first of all thank you so much for this fantastic theme, the last version is especially great given how configurable it is.

I was wondering if the fonts could also be made configurable. From what I can tell, this would mean simply replacing all the hardcoding of Noto Sans with `font.family: config.displayFont` and then adding the displayFont option in theme.conf.

I tested it out myself on the latest version and it seems to have worked fine (but perhaps the user should be warned not to use non-systemwide fonts)

**Comment by MarianArlt** [comment]
As you mentioned this is rather easy to implement. Personally, as a designer I cringe before such customizations because people tend to customize things to a level where it's not a smooth user experience any more. But: I realize and know that the best fact about Linux is just that. It can be mine. The way _I_ like it.
This setting especially is pretty dangerous in terms of legibility and interface readability.
Nevertheless it's a feature and as such I'll have it implemented in the next release. Care must be taken though to write the correct annotation in the config of the font name. This can be confusing for people not used to font management.

**Comment by MarianArlt** [comment]
Added this in the latest version. Please upgrade to 0.5.4. b2188228cda182a2cf7830761d8161aed6b3f0fd
