### ISSUE TITLE
Can't set custom background in v0.5.4

### ISSUE THREAD

**Issue by r3b311i0n** [MarianArlt/kde-plasma-chili#19]
Setting a custom background using System Settings or by editing the `theme.conf.user` file has no effect and the default background is used instead. Downgrading to `0.5.3` fixes the issue.

#### env:

Arch Linux
Installed using [AUR PKGBUILD](https://aur.archlinux.org/packages/sddm-theme-kde-plasma-chili)
sddm: 0.18.0
plasma: 5.14.2

**Comment by r3b311i0n** [comment]
Yup, using capitalised `Background` fixes it. And thanks for the responses! :smile:

**Comment by MarianArlt** [comment]
Yes indeed, when creating the theme.conf.user file the variable is called "background" and I lately wanted to unify my theme.conf variables to be all uppercase. I didn't test enough with this. To fix this I'll rewrite the logic a little so that the lowercase background variable from theme.conf.user takes precedence. Thanks @r3b311i0n for pointing this out.
And to @mockroot for helping! I'll fix this asap!

P.D.: I actually realize I did this comparison right by default for my latest two themes ^^;

**Comment by MarianArlt** [comment]
Github release is up to date with v0.5.5. 279cdf8e3fbe0cea0e8462c22e0e9f61f0745e50 should fix this. Uploading to opendesktop now.
